mod field;
mod elliptic_curve;

use elliptic_curve::Point;
use field::Field101;

fn main() {
    let g = Point::new(Field101::new(1), Field101::new(2));
    println!("Subgroup Generated by G ({:?}):", g);

    let mut current = Point::Infinity;
    let mut subgroup = Vec::new();

    for i in 0.. {
        if subgroup.contains(&current) {
            break;
        }

        println!("{}G = {:?}", i, current);
        subgroup.push(current);
        current = current.add(g);
    }

    println!("\nSubgroup Order: {}", subgroup.len());
}
